---
title: "PUBH 7462 Homework 3"
author: "Chris Wojan"
date: "2/16/2022"
output: github_document
---

```{r setup, include=FALSE}

## Load libraries
library(tidyverse)
library(janitor)
library(gt)

## Working directory for .RMD
knitr::opts_knit$set(echo = TRUE,
                     root.dir = rprojroot::find_rstudio_root_file())

## Set knitr options
knitr::opts_chunk$set(echo = TRUE)

## Set Theme for ggplot2 - centers title and legend at bottom by default
theme_set(theme_bw() + 
          theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom"))

## Set Scientific notation output and decimal places for knitr
options(scipen = 999)
options(digits = 4)

```

### Setup

```{r read_data, echo = TRUE, message = FALSE}

## Read in the data
instacart <- read_csv("./data/instacart.csv")

```

### Problem 3.1

```{r prob_3.1, echo = TRUE, message = FALSE}

## Draw table from data
instacart %>%
  ## Group by order and calculate order chracteristics
  group_by(order_id) %>%
  summarise("Days Since Last Order" = days_since_prior_order,
            "Number of Items" = n(),
            "Number of Aisles" = length(unique(aisle_id)),
            "Number of Departments" = length(unique(department_id)),
            "Order Number" = order_number,
            "Percent of Items Reordered" = sum(reordered)/n()) %>%
  ## Filter out duplicates and ungroup
  unique() %>%
  ungroup() %>%
  ## Change data from wide to long; collecting each order variable into a single column 
  pivot_longer(cols = -order_id, names_to = "variable", values_to = "value") %>%
  ## Calculate summary statistics across all orders
  group_by(variable) %>%
  summarise(Mean = mean(value),
            Median = median(value),
            S.D. = sd(value)) %>%
  ## Rename column and create titled table
  rename("Order Characteristic" = variable) %>%
  gt() %>%
  tab_header(title = "Summary of Orders") %>%
  as_raw_html()

```

### Problem 3.2

```{r prob_3.2, echo = TRUE, message = FALSE, fig.height = 16, fig.width = 8}

## Draw plot from data
instacart %>%
  ## Determine number of sales from each aisle, and order the aisles by that value
  count(aisle) %>%
  mutate(aisle = str_to_title(aisle),
         aisle = factor(aisle),
         aisle = fct_reorder(aisle, n)) %>%
  ## Draw plot
  ggplot() +
  ## Draw "lollipop" plot of sales by aisle
  geom_point(aes(x = n, y = aisle, color = n)) +
  geom_segment(aes(x = 0, xend = n, y = aisle, yend = aisle, color = n)) +
  ## Set visual style of plot
  scale_color_continuous(name = "Total Number of of Products Sold") +
  scale_x_continuous(expand = expansion(mult = c(0, 0.025))) +
  labs(x = "Total Number of of Products Sold",
       y = "Aisle",
       title = "Store Aisles by Product Sales") +
  theme(legend.key.width = unit(1, "cm"))

```

### Problem 3.3

```{r prob_3.3, echo = TRUE, message = FALSE, fig.width = 10}

## Draw plot from data
instacart %>%
  ## Determine number of sales by aisle and department
  count(department, aisle) %>%
  ## Reformat aisle/dept names, order department factor by number of sales
  mutate(aisle = str_to_title(aisle),
         department = str_to_title(department),
         department = factor(department),
         department = fct_reorder(.f = department, .x = n, .fun = sum, .desc = TRUE)) %>%
  ## Take only the top 6 departments by sales
  filter(department %in% levels(department)[1:6]) %>%
  ## Sort aisles by number of sales within department
  group_by(department) %>%
  arrange(desc(n), .by_group = TRUE) %>%
  mutate(aisle_ord = row_number()) %>%
  ungroup() %>%
  ## Take only the top 6 aisles by sales for each department
  filter(aisle_ord < 7) %>%
  ## Draw plot
  ggplot() +
  ## Draw labelled lollipops for each aisle
  geom_point(aes(x = n, y = aisle_ord, color = factor(aisle_ord))) +
  geom_text(aes(x = 2000, y = aisle_ord + 0.5, label = aisle, color = factor(aisle_ord)), 
            size = 2, hjust = "inward") +
  geom_segment(aes(x = 0, xend = n, y = aisle_ord, yend = aisle_ord, color = factor(aisle_ord))) +
  ## Separate plot into panels for each of 6 departments
  facet_wrap(vars(department)) +
  ## Set visual style of plot
  scale_color_hue(h = c(100, 180), l = 50, c = 150,
                   name = "Sales Rank \nwithin Department") +
  scale_x_continuous(expand = expansion(mult = c(0, 0.025))) +
  scale_y_continuous(trans = "reverse") +
  guides(color = guide_legend(nrow = 6)) +
  labs(x = "Number of of Products Sold",
       y = "",
       title = "Top Six Aisles in Top Six Departments by Sales") +
  theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        panel.spacing.x = unit(6, "mm"), legend.position = "right")

```

### Problem 3.4

Note: While the five aisles in the table are the top five most popular aisles sales-wise, they are ordered within the table by the total sales of only their top five products.

```{r prob_3.4, echo=TRUE, message=FALSE}

## Create tibble of top 5 aisles, top 5 products, by sales
aisle_products <- instacart %>%
  ## Determine number of sales by product and aisle
  count(aisle, product_name) %>%
  ## Order aisle factor by total sales
  mutate(aisle = str_to_title(aisle),
         aisle = factor(aisle),
         aisle = fct_reorder(.f = aisle, .x = n, .fun = sum, .desc = TRUE)) %>%
  ## Take only the top 5 aisle by sales
  filter(aisle %in% levels(aisle)[1:5]) %>%
  ## Sort the products by number of sales within aisles
  group_by(aisle) %>%
  arrange(desc(n), .by_group = TRUE) %>%
  mutate(product_ord = row_number()) %>%
  ## Take only the top 5 products for each of 5 aisles
  filter(product_ord < 6) %>%
  ungroup() %>%
  ## Reorder the aisle factor now by total sales only including each aisle's top 5 products
  mutate(aisle = factor(as.character(aisle)),
         aisle = fct_reorder(.f = aisle, .x = n, .fun = sum, .desc = TRUE)) %>%
  arrange(aisle, desc(n)) %>%
  ## Make table better for visual presentation
  select(aisle, product_name, n) %>%
  rename(Product = product_name,
         Sales = n)

## Determine highest value of sales among products
max_sales <- max(aisle_products$Sales)

## Draw table from aisle/product data
aisle_products %>%
  ## Group the table into subtabs for each aisle
  group_by(aisle) %>%
  gt() %>%
  tab_header(title = "Top 5 Products from Top 5 Aisles in Products Sold") %>%
  ## Color sales tabs by amount
  data_color(columns = Sales,
             colors = scales::col_numeric(
               palette = c("white", "blue"),
               domain = c(0, max_sales)
             )
  ) %>%
  as_raw_html()
  
```








